### PR TITLE
Allow setting path when uploading file

### LINKED ISSUE #1105: Create New Path in Bucket Explorer
Add the ability to create new paths to bucket explorer

### PR DESCRIPTION
**Pull request by jmthomas**

### CODE REVIEW

**Comment by jmthomas** [comment]
Screenshot 2024-02-23 at 5 12 14 PM

**Comment by ryanmelt** [comment]
This is great!  What the ticket was asking for was the ability to create empty directories though, which I didn't think was possible, but it looks like it is.

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Changes look good.  Please investigate adding button to create path without a file.

**Comment by jmthomas** [comment]
> Changes look good. Please investigate adding button to create path without a file.

Doesn't really make sense with Bucket technology to create a directory without a file. That's why I did the file path thing. The ability to upload files only ever worked with Buckets not volumes so I think this is how it should work.

**Comment by ryanmelt** [comment]
People wanted bucket technology to work like a filesystem which is why they created a way to create empty folders.  This change does not address the request of ticket #1105

**Pull request merged**
