### PR TITLE
Makefile

### PR DESCRIPTION
**Pull request by haisamido**

### CODE REVIEW

**Comment by ryanmelt** [comment]
What is the benefit of adding a Makefile?

**Comment by haisamido** [comment]
> What is the benefit of adding a Makefile?

self describing. Run make and you'll see.

**Comment by ryanmelt** [comment]
I see no benefit to this over our ./openc3.sh script?  It just wraps that.

**Comment by haisamido** [comment]
> I see no benefit to this over our ./openc3.sh script? It just wraps that.

It wraps it for now, but the content of openc3.sh could ideally be directly in the Makefile, and openc3.sh can go away. IMHO.

**Comment by ryanmelt** [comment]
This seems like something to just keep as part of your personal COSMOS config.  
Closing unless we see more interest in a Makefile.

**Pull request closed without merging**
