### PR TITLE
Fix applying subsettings, fix LimitscolumnWidget

### LINKED ISSUE #1389: Limits Example Screen Issues
The Vertical Limits Bar appears as all green.
Also, the subsettings appear to not be working

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1389

### CODE REVIEW

**Comment by jmthomas** [comment]
Screenshot 2024-07-13 at 1 42 30 PM

**Review by ryanmelt — APPROVED** [review]
Assuming Playwright passes on next run.

**Comment by ryanmelt** [comment]
Same playwright failure twice in a row

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Fix playwright

**Pull request merged**
