### PR TITLE
Minio console working

### PR DESCRIPTION
**Pull request by jmthomas**

### CODE REVIEW

**Review by ryanmelt — APPROVED** [review]

**Comment by jeffstjean** [comment]
Is this related to an issue introduced in d037355e310cf5646ee397dd40254e72841bb778 relating to viewing contents of a bucket using the MinIO? I noticed it would be stuck loading and not show any objects. Didn't want to open a new issue if this resolves it

**Comment by ryanmelt** [comment]
This appear to fully fix minio console

**Comment by jeffstjean** [comment]
Thanks for the quick turnaround! Is this targeting v5.4.2? We're doing a big upgrade from a development release and we'll either downgrade from v5.4.1 to v5.4.0 for now or just wait a bit longer for v5.4.2

**Comment by ryanmelt** [comment]
I just kicked off the 5.4.2 release.  Should be done about midnight.

**Comment by ryanmelt** [comment]
In about 2 and a half hours...

**Pull request merged**
