### PR TITLE
Dataviewer components

### PR DESCRIPTION
**Pull request by jmthomas**
DataViewer now supports custom user defined components (which are defined as Widgets). Each component can now take multiple packets rather than one. Thus I removed the ability to show more than 1 packet because as they are streamed in you don't really know which is which. History is still there and the search bar now works to filter the results.

I'm going to pull a lot of the DumpComponent into a base widget called HistoryComponent to make the default case of simply modifying the text output a lot easier. If you want to create a fully custom widget you can mixin Component and go to town. 

I also still need to update all the playwright tests.

### CODE REVIEW

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Lost the number of packets to scroll.  That needs to come back.  Also should default to more than 1.   (10 or 100?).

Probably also make height 100% to take up the whole pane.

**Comment by jmthomas** [comment]
> Lost the number of packets to scroll.  That needs to come back.  Also should default to more than 1.   (10 or 100?).
> 
> 
> 
> Probably also make height 100% to take up the whole pane.

Number of packets doesn't work when you subscribe to more than one so I took it out. Could put back and just let it only work if they subscribe to one?

**Comment by ryanmelt** [comment]
Its how many packets are rendered... I don't see why that matters with how many are subscribed.

**Comment by ryanmelt** [comment]
This is great.  The only thing I'm not sure about is the name "lastReceived".  Got any better names for that?

**Pull request merged**
