### PR TITLE
Add docker network to scripts

### LINKED ISSUE #561: Add cli irb to the "openc3-cosmos-network"
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
The docker container that is brought up with the cli irb is not connected to the docker network.

**Describe the solution you'd like**
 I think you just need to add the below argument to the docker run command:
--network openc3-cosmos-network

### PR DESCRIPTION
**Pull request by ryanmelt**
closes #561

### CODE REVIEW

**Review by jmthomas — APPROVED** [review]
Why is this necessary?

**Comment by ryanmelt** [comment]
This allows the cli to interact with the other containers.

**Comment by jmthomas** [comment]
> This allows the cli to interact with the other containers.

Was the CLI broken in specific use cases?

**Comment by ryanmelt** [comment]
I guess.  See #561.

**Pull request merged**
