### PR TITLE
Update SR file open / save dialog

### LINKED ISSUE #1551: Update SR File-Save As for clarity
Update Script Runner File-Save As to note filename needs a valid extension (.rb or .py). Maybe explain the process at the top. It's not a very intuitive dialog to navigate to the directory and then type in the filename.

### PR DESCRIPTION
**Pull request by jmthomas**
closes #1551

### CODE REVIEW

**Comment by jmthomas** [comment]
Screenshot 2024-09-18 at 9 52 19 PM
Screenshot 2024-09-18 at 9 52 47 PM

**Comment by ryanmelt** [comment]
Can we update the save to only include the filename at the bottom, and have the top be a folder/file selector.   (Like most other tools)

**Review by ryanmelt — CHANGES_REQUESTED** [review]
Can we get this to work where only the filename is entered below, and the final result takes into account the selected folder for you.

**Comment by jmthomas** [comment]
I think we should aim to rework this dialog after the Vue 3 transition is finished. I don't want to get into a bunch of new html and vuetify tree stuff that might have to change anyway.

**Comment by ryanmelt** [comment]
That's fine, but create another ticket for it.

**Review by ryanmelt — APPROVED** [review]

**Pull request merged**
